BASE: ['ddsm_base.yaml']
DATA:
  dataset: patch_data
  num_workers: 1
  batch_size: 32
  class_num: 5
  elastic_param: 500
  data_dir: /home/xumingjie/Desktop/DDSM_DATA/patch_set/
  aug_prob: 0.5
  img_mean: [0.485]
  img_std: [0.229]
  repeat_channel: True
MODEL:
  blocks:
    encoder:
      name: swin_transformer
      pretrained: NULL
      weights: NULL
      args:
        pretrained: 'logs/patch_train_swin/version_0/checkpoints/best-epoch=66-lesion=0.926.ckpt'
        embed_dim: 128
        window_size: 7
        depths: [ 2, 2, 18, 2 ]
        num_heads: [ 4, 8, 16, 32 ]
      optimizer: SGD
      scheduler: step
      learning_rate: 0.0001
      lr_decay_rate: 0.01
      lr_decay_steps: 5
      weight_decay: 0.0001
      beta1: 0.9
    decoder:
      name: empty_header
      pretrained: NULL
      weights: NULL
  losses:
    lesion: crossentropy
  loss_scale: 
    lesion: 1
  metrics: 
    lesion: f1score