BASE: ['base.yaml']
DATA:
  dataset: csaw_data
  num_workers: 6
  batch_size: 4
  class_num: 2
  pic_size: [512,512]
  elastic_param: 500
  data_dir: /root/autodl-tmp/csaw_set
  aug_prob: 0.5
  img_mean: [0.485]
  img_std: [0.229]
  repeat_channel: True
MODEL:
  blocks:
    encoder:
      name: resnet_csail
      pretrained: NULL
      weights: NULL
      args:
        pretrained: True
      optimizer: SGD
      scheduler: step
      learning_rate: 0.01
      lr_decay_rate: 0.5
      lr_decay_steps: 50
      weight_decay: 0.0001
      beta1: 0.9
    decoder:
      name: uper_net
      pretrained: NULL
      weights: NULL
      args:
        seg_size: [512, 512]
        output_switch: 
          pathology: False
          lesion: True
          rad_time: True         
        nr_classes:
          pathology: 1
          lesion: 2
          rad_time: 1
  losses:
    lesion: focal
    rad_time: mse
  loss_scale: 
    lesion: 10
    rad_time: 1
  metrics: 
    lesion: accuracy
    rad_time: cosine