BASE: ['base.yaml']
DATA:
  dataset: csaw_data
  num_workers: 6
  batch_size: 32
  class_num: 5
  crop_weight: [0.7,0.2,0.1]
  positive_thr: 0.05
  elastic_param: 500
  data_dir: /root/autodl-tmp/csaw_set
  aug_prob: 0.5
  img_mean: [0.485]
  img_std: [0.229]
  repeat_channel: True
MODEL:
  blocks:
    encoder:
      name: swin_transformer
      pretrained: NULL
      weights: NULL
      args:
        pretrained: '/root/swin_base_patch4_window7_224_22k.pth'
        embed_dims: 128
        window_size: 7
        depths: [2, 2, 18, 2]
        num_heads: [4, 8, 16, 32]
      optimizer: SGD
      scheduler: step
      learning_rate: 0.01
      lr_decay_rate: 0.5
      lr_decay_steps: 50
      weight_decay: 0.0001
      beta1: 0.9
    decoder:
      name: uper_net
      pretrained: NULL
      weights: NULL
      args:
        nr_classes:
          pathology: 1
          lesion: 2
          rad_time: 1
  losses:
    lesion: focal
    rad_time: mse
  loss_scale: 
    lesion: 10
    rad_time: 1
  metrics: 
    lesion: accuracy
    rad_tome: cosine